# Generated by Django 4.2.5 on 2023-10-27 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_article_create_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, default='defaults/default.jpeg', upload_to='articles/'),
        ),
    ]
